#!/bin/bash


# sprawdzic, bo dla niezalogowanego moze dac pusty wpis do credentials

aws sts assume-role --role-arn arn:aws:iam::104024231658:role/ZaszyfrowanyBucketRole --role-session-name "RoleSession1" --profile lobo101-LoaderS3User \
| awk -F:  '
                BEGIN { RS = "[,{}]" ; print "[lobo101-zaszyfrowany]"}
                /:/{ gsub(/"/, "", $2) }
                /AccessKeyId/{ print "aws_access_key_id = " $2 }
                /SecretAccessKey/{ print "aws_secret_access_key = " $2 }
                /SessionToken/{ print "aws_session_token = " $2 }
' >> ~/.aws/credentials
