#!/bin/bash

exit 1

DST="cde"
if [ ! -z "$1" ]; then
    DST=$1
    echo "desctination $DST"
fi

rsync -av /home/lg/spx101/dotfiles/.aws/config lg@$DST:/home/lg/.aws/
rsync -av ~/.aws/credentials lg@$DST:/home/lg/.aws/
rsync -av ~/.kube/{c2a,c2a-dev,c2a-int,config,minicube} lg@$DST:/home/lg/.kube/
rsync -av ~/bin/ecr-login lg@$DST:/home/lg/

#rsync -av ~/.pgpass lg@cde:/home/lg/
