#!/bin/bash

dowork() {
    echo "Processing repo :: gh repo clone $1"
    REPONAME=$(echo $1 | cut -d/ -f2)
    if [ -d $REPONAME ]; then
        (cd $REPONAME ; git pull)
    else
        gh repo clone $1
    fi
    sleep 0.01
}
export -f dowork

CURRENT_DIR=$(basename "$PWD")

if [[ "$CURRENT_DIR" != gh--* ]]; then
    echo "Error: Directory name does not contain 'gh--'"
    exit 1
fi

STRING1=$(echo $CURRENT_DIR | sed 's/--/#/g')
NAMESPACE=$(echo $STRING1 | cut -d'#' -f2)
PREFIX=$(echo $STRING1 | cut -d'#' -f3)
echo "run: Current repository namespace: $NAMESPACE"
echo "Current repository prefix: $PREFIX"

if [ ! -z $PREFIX ]; then
    GH_CLONE_ARGS="-n ${NAMESPACE} -f ${PREFIX}"
else
    GH_CLONE_ARGS="-n ${NAMESPACE}"
fi

echo "run: gh-repo-list -ojson $GH_CLONE_ARGS"

REPOS_LIST=$(gh-repo-list -ojson $GH_CLONE_ARGS | jq -r '.[].full_name')

parallel --jobs 6 dowork ::: "${REPOS_LIST[@]}"


# echo "Processing repos with awsp- prefix"
# REPOS_LIST=$(echo $REPOS | jq -r 'select(.nameWithOwner | startswith("Ringier-Axel-Springer-PL/awsp-")) | .nameWithOwner')
# parallel --jobs 4 dowork ::: "${REPOS_LIST[@]}"

# #~/.config/Code/User/globalStorage/alefragnani.project-manager/projects.json

# #[
# #    {
# #		"name": "sdk-lgtest-action1",
# #		"rootPath": "/home/lg/gh/sdk-lgtest-action1",
# #		"paths": [],
# #		"tags": ["lgtest"],
# #		"enabled": true
# #	},
