#!/bin/bash

echo "Example $0 - master"
echo "Example $0 REPONAME main"

repo=$1
branch=$2

if [ -z "$repo" ] || [ "$repo" == "-" ]; then
    repo=$(basename "$PWD")
fi

user=ringier-axel-springer-pl

echo "repository: $user/$repo"

# gh api repos/$user/$repo/actions/runs --paginate -q '.workflow_runs[] | select(.head_branch == "main") | "\(.id)"' | xargs -I % gh api repos/$user/$repo/actions/runs/% -X DELETE

# Pobierz listę ID workflow_runs dla głównej gałęzi
run_ids=$(gh api repos/$user/$repo/actions/runs --paginate -q ".workflow_runs[] | select(.head_branch == \"$branch\") | .id")

echo $run_ids

# Policz, ile runów zostanie usuniętych
total=$(echo "$run_ids" | wc -l)
current=0

# Usuń każde ID i zaktualizuj pasek postępu
echo "Usuwanie workflow runs..."
for run_id in $run_ids; do
  echo $run_id
  gh api repos/$user/$repo/actions/runs/$run_id -X DELETE
  current=$((current + 1))
  # Wyświetl pasek postępu
  printf "\rProgress: [%-50s] %d%%" "$(head -c $((current * 50 / total)) < /dev/zero | tr '\0' '#')" $((current * 100 / total))
done

# Zakończenie
echo -e "\nGotowe!"
