#!/bin/bash

NS=$1

echo "Please contact the following team members for assistance: ($NS)"

_MEMBERS="/tmp/namespace-prod-$NS-members"
if [ ! -f "$_MEMBERS" ]; then
  gh api /orgs/Ringier-Axel-Springer-PL/teams/namespace-prod-$NS/members > "$_MEMBERS"
fi

cat "$_MEMBERS" | jq -r '.[] | [.url,.html_url] | @csv' | while read i; do
  _url=$(echo $i | cut -d, -f1 | tr -d '"')
  _html_url=$(echo $i | cut -d, -f2 | tr -d '"')
  echo -n "$_html_url   |  "
  curl -Ss $_url | jq -r '[.login,.name] | @csv'
done

