#!/bin/bash

echo "
git pull
git checkout -b XXX
git push origin XXX
git branch -a

// delete branch locally
git branch -d localBranchName

// delete branch remotely
git push origin --delete remoteBranchName
"
