#!/bin/bash

sudo apt-get install dirmngr
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch release-v0.10.0

#echo '. $HOME/.asdf/asdf.sh' >> ~/.bashrc
#echo '. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc

# https://github.com/asdf-community/asdf-direnv
# https://blog.sighup.io/manage-tools-with-ease-direnv-asdf/
