#!/bin/sh

#if [ -z $1 ]; then
#    echo "kubectl-get-events -n NAMESPACE --watch"
#    exit 1
#fi
#[ -z $2 ] && { echo "kubectl-get-events -n NAMESPACE --watch"; exit 1; }


kubectl get events --sort-by='.lastTimestamp' $@ 



