#!/bin/bash

directories=( "/home/lg/zaszyfrowany" "/home/lg/zaszyfrowany-docs" "/home/lg/zaszyfrowany-rasp" "/home/lg/bin" "/home/lg/scripts" )

~/bin/my-status

for base_dir in "${directories[@]}"; do
    for dir in $(find "$base_dir" -type d -name ".git"); do
        repo=$(dirname "$dir")
        cd "$repo" || continue
        status=$(git status --porcelain)
        if [ -n "$status" ]; then
            echo -e "Repository $repo \e[31mhas uncommitted or unpushed changes.\e[0m"
        else
            echo "Repository $repo is clean. Pulling latest changes..."
            git pull
        fi
    done
done

for base_dir in "${directories[@]}"; do
    for dir in $(find "$base_dir" -type d -name ".git"); do
        repo=$(dirname "$dir")
        cd "$repo" || continue
        status=$(git status --porcelain)
        if [ -n "$status" ]; then
            echo "Changes to be committed and pushed in $repo:"
            git status --short

            read -p "Do you want to commit and push local changes? (yes/no) " answer
            if [ "$answer" == "yes" ]; then
                echo "Committing and pushing changes in $repo..."
                git add .
                git commit -m "Auto-commit"
                git push
            fi
        fi
    done
done

~/bin/my-status