#!/bin/bash

# Na Wayland xclip zazwyczaj nie działa, ponieważ obsługuje tylko X11.
# Na Wayland polecane są narzędzia takie jak wl-clipboard (wl-copy, wl-paste).

#killall -u $USER xclip 1>/dev/null 2>/dev/null

set -eo pipefail
app="pass-from-gpg"

FILE="$HOME/zaszyfrowany/$1"
if [ ! -f "$FILE" ]; then
    notify-send -t 2000 -a $app -i ~/icons/dialog-warning.png "brak pliku"
    echo "missing password $FILE"
    exit 0
fi

notify-send -t 2000 -i ~/icons/dialog-password.png -a pass-from-gpg "waiting for yubikey"

pass=$(gpg -d $FILE 2>/dev/null | grep 'password:' | cut -d":" -f2 | tr -d '[:space:]' | tr -d '\n')

#echo $pass

if [ -z "$pass" ]; then
    notify-send -t 2000 -a pass-from-pgp -i ~/icons/dialog-error.png "missing password"
    echo "missing password"
    exit 0
fi

#echo -n $pass | xclip -r -l 5 -selection clipboard
echo -n $pass | wl-copy
notify-send -t 1000 -a $app -i ~/icons/selection-checked.png "pass copied"

#xdotool key ctrl+v
i=0
while [ $i -lt 5 ]; do
    sleep 1
    i=$((i + 1))
    echo "Waiting $i"
done

notify-send -t 1000 -a $app -i ~/icons/selection-checked.png "clean"
#echo -n "" | xclip -l 1 -selection clipboard
trap 'echo -n "-" | wl-copy' EXIT

#notify-send -t 1000 -a $app -i ~/icons/selection-checked.png "OK"

