#!/bin/bash

OPT="-k $HOME/.keepass/rasp.key --no-password $HOME/workspace/keepass/rasp.kdbx"

if [ "$1" == "" ];then
    keepassxc-cli ls $OPT
    exit 0
fi
KEY=$1

RESULT=$(keepassxc-cli show --all $OPT $KEY)
echo "---------------------------------"
printf "%s\n" "$RESULT"
echo "---------------------------------"

if echo "$RESULT" | grep -q "otp:"; then
    OPT="--totp $OPT"
fi

keepassxc-cli clip $OPT $KEY

