#!/bin/bash


if [ "$1" == "-r" ]; then
    rm -rf $HOME/sdk-action-lint-yaml
fi

if [ ! -d $HOME/sdk-action-lint-yaml ]; then
    #gh repo clone Ringier-Axel-Springer-PL/sdk-action-lint-yaml $HOME/sdk-action-lint-yaml -- --depth 1 --sparse
    gh repo clone Ringier-Axel-Springer-PL/sdk-action-lint-yaml $HOME/sdk-action-lint-yaml -- --depth 1
fi

yamllint --no-warnings -c $HOME/sdk-action-lint-yaml/src/config.yaml .


