#!/bin/bash


#gh release download v1 --repo Ringier-Axel-Springer-PL/sdk-action-lint-yaml --archive=zip


if [ ! -d $HOME/sdk-action-lint-yaml ]; then
gh repo clone Ringier-Axel-Springer-PL/sdk-action-lint-yaml $HOME/sdk-action-lint-yaml
fi

yamllint -c $HOME/sdk-action-lint-yaml/src/config.yaml .


